feat: Updated .github/workflows/lock-issue.yml

diff --git a/.github/workflows/lock-issue.yml b/.github/workflows/lock-issue.yml
--- a/.github/workflows/lock-issue.yml
+++ b/.github/workflows/lock-issue.yml
@@ -34,32 +34,9 @@ jobs:
         with:
           github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
           issue-inactive-days: '365'
-          exclude-issue-created-before: ''
-          exclude-issue-created-after: ''
-          exclude-issue-created-between: ''
-          exclude-issue-closed-before: ''
-          exclude-issue-closed-after: ''
-          exclude-issue-closed-between: ''
-          include-any-issue-labels: ''
-          include-all-issue-labels: ''
-          exclude-any-issue-labels: ''
-          add-issue-labels: ''
-          remove-issue-labels: ''
-          issue-comment: ''
-          issue-lock-reason: 'resolved'
-          pr-inactive-days: '365'
-          exclude-pr-created-before: ''
-          exclude-pr-created-after: ''
-          exclude-pr-created-between: ''
-          exclude-pr-closed-before: ''
-          exclude-pr-closed-after: ''
-          exclude-pr-closed-between: ''
-          include-any-pr-labels: ''
-          include-all-pr-labels: ''
-          exclude-any-pr-labels: ''
-          add-pr-labels: ''
-          remove-pr-labels: ''
-          pr-comment: ''
-          pr-lock-reason: 'resolved'
-          process-only: ''
-          log-output: false
+      - name: Check BOT_GITHUB_TOKEN secret
+        run: |
+          if [[ -z "${{ secrets.BOT_GITHUB_TOKEN }}" ]]; then
+            echo "Error: The BOT_GITHUB_TOKEN secret is not set. Please set this secret in the repository settings."
+            exit 1
+          fi
